### PR TITLE
Adding analysis only param

### PR DESCRIPTION
**Pull request by josenavas**
Modifying the command object and the register call so the command can register as a command that is only available in the analysis pipeline.

### CODE REVIEW

**Comment by antgonza** [comment]
changes look fine but we have unrelated errors that will be good to fix so tests are run ...

**Comment by josenavas** [comment]
@antgonza the current failures on the tests are due to some error generating the documentation in Qiita. Can you take a look, given that you're recently working with the Qiita documentation? I'm wondering if there is something missing on the setup.py from Qiita or similar. Thanks!

**Comment by josenavas** [comment]
@antgonza this should be ready

**Comment by josenavas** [comment]
Up to you

**Pull request merged**
